### PR TITLE
Desity -> Density

### PR DESCRIPTION
**Pull request by NaridaL**
**Purpose of the pull request**  
Fix Typo in UI

**Description about the pull request**  
*The description about this pull request.*

**Additional comments** [Optional]

### CODE REVIEW

**Review by nutti — APPROVED** [review]
LGTM

**Comment by nutti** [comment]
@NaridaL 

Thanks for your contribution!
I merged your PR.

We can add your name ("NaridaL" or other name) to the author on `bl_info` if you want.

https://github.com/nutti/Magic-UV/blob/7d20c4374a125d712f124e8c10295fa420420ede/src/magic_uv/__init__.py#L13-L16

What do you think?

**Comment by NaridaL** [comment]
Thanks, that's OK, this PR was trivial 🙂 .

**Comment by nutti** [comment]
OK. I will keep the current code.
If you change the mind, please let me know.

**Pull request merged**
